"""Emit the stripped-thumbnail JPEG header as a Rust byte array.

Generated rather than transcribed: the header is 623 bytes of quantisation and
Huffman tables, and a single wrong nibble produces an image that still decodes
but looks wrong, which no test would catch by eye.

    python tools/gen_jpeg_header.py > crates/tgx-media/src/jpeg_header.rs
"""
import sys

sys.path.insert(0, r"C:\Users\Kosta\Projekti\telegram")
from telethon import utils  # noqa: E402

# Round-trip a minimal payload to recover the exact header the client uses.
probe = bytes([1, 0x11, 0x22])
out = utils.stripped_photo_to_jpg(probe)
assert out.endswith(b"\xff\xd9")
header = bytearray(out[:-2])
# Undo the two patched bytes so the constant is the pristine template.
assert header[164] == 0x11 and header[166] == 0x22
header[164] = 0
header[166] = 0

print("//! The fixed JPEG header Telegram strips from every embedded thumbnail.")
print("//!")
print("//! Generated by `tools/gen_jpeg_header.py`, not transcribed. Every")
print("//! stripped thumbnail shares the same quantisation and Huffman tables, so")
print("//! Telegram sends them once — in the client — rather than on every")
print("//! thumbnail. Putting them back is a splice, not a conversion.")
print("//!")
print("//! Ported from Telegram Desktop via Telethon's `stripped_photo_to_jpg`.")
print()
print(f"/// {len(header)} bytes. Offsets 164 and 166 carry the width and height.")
print(f"pub const HEADER: [u8; {len(header)}] = [")
for i in range(0, len(header), 12):
    row = ", ".join(f"0x{b:02x}" for b in header[i:i + 12])
    print(f"    {row},")
print("];")
print()
print("/// Offset of the width byte inside [`HEADER`].")
print("pub const WIDTH_OFFSET: usize = 164;")
print("/// Offset of the height byte inside [`HEADER`].")
print("pub const HEIGHT_OFFSET: usize = 166;")
