r"""Emit the stripped-thumbnail JPEG header as a Rust byte array.

Generated rather than transcribed: the header is 623 bytes of quantisation and
Huffman tables, and a single wrong nibble produces an image that still decodes
but looks wrong, which no test would catch by eye.

    python tools/gen_jpeg_header.py

It writes crates/tgx-media/src/jpeg_header.rs itself instead of printing for a
`>` redirect, and it emits plain ASCII, LF endings and 16 bytes to a row. The
first version did none of those and so did not round-trip: redirecting on
Windows re-encoded the em dashes as cp1252 (leaving a .rs file that was not
even valid UTF-8) and turned every LF into CRLF, and the 12-byte rows were
reflowed to 16 by rustfmt, which fills the 100-column width. Three diffs
against a file whose whole claim is that it is reproducible.

telethon is not on the system path; it lives in the Python original's venv:

    C:\Users\Kosta\Projekti\telegram\.venv\Scripts\python.exe tools/gen_jpeg_header.py
"""
import pathlib
import sys

ORIGINAL = pathlib.Path(r"C:\Users\Kosta\Projekti\telegram")
sys.path.insert(0, str(ORIGINAL))
sys.path.insert(0, str(ORIGINAL / ".venv" / "Lib" / "site-packages"))

from telethon import utils  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parents[1] / "crates" / "tgx-media" / "src" / "jpeg_header.rs"

# Decoded from the header below, not assumed: SOF0 is `FF C0` at 158, followed
# by a 2-byte segment length, one precision byte, then height at 163..=164 and
# width at 165..=166, both big-endian. Telethon -- and tdesktop before it --
# patches stripped[1] into 164 and stripped[2] into 166, so 164 is the height.
# These two were named the other way round until the header was walked.
SOF0 = 158
HEIGHT_OFFSET = 164
WIDTH_OFFSET = 166

# Round-trip a minimal payload to recover the exact header the client uses.
probe = bytes([1, 0x11, 0x22])
out = utils.stripped_photo_to_jpg(probe)
assert out.endswith(b"\xff\xd9")
header = bytearray(out[:-2])
assert header[SOF0:SOF0 + 2] == b"\xff\xc0", "SOF0 moved; the offsets are guesses now"
assert header[HEIGHT_OFFSET] == 0x11 and header[WIDTH_OFFSET] == 0x22
# Undo the two patched bytes so the constant is the pristine template.
header[HEIGHT_OFFSET] = 0
header[WIDTH_OFFSET] = 0

lines = [
    "//! The fixed JPEG header Telegram strips from every embedded thumbnail.",
    "//!",
    "//! Generated by `tools/gen_jpeg_header.py`, not transcribed. Every stripped",
    "//! thumbnail shares the same quantisation and Huffman tables, so Telegram sends",
    "//! them once -- in the client -- rather than on every thumbnail. Putting them",
    "//! back is a splice, not a conversion: measured at 0.9us each.",
    "//!",
    "//! Ported from Telegram Desktop via Telethon's `stripped_photo_to_jpg`.",
    "//!",
    "//! ASCII, LF and 16 bytes to a row are load-bearing: they are what the",
    "//! generator has to emit for a regeneration to reproduce this file byte for",
    "//! byte instead of landing three diffs on it.",
    "",
    f"/// {len(header)} bytes. Decoded rather than assumed: SOF0 (`FF C0`) starts at {SOF0},",
    f"/// so {HEIGHT_OFFSET} is the height's low byte and {WIDTH_OFFSET} is the width's.",
    f"pub const HEADER: [u8; {len(header)}] = [",
]
for i in range(0, len(header), 16):
    row = ", ".join(f"0x{b:02x}" for b in header[i:i + 16])
    lines.append(f"    {row},")
lines += [
    "];",
    "",
    "/// Offset of the **height**'s low byte inside [`HEADER`].",
    "///",
    f"/// SOF0 begins at {SOF0} and lays out `FF C0`, a 2-byte segment length, one",
    "/// precision byte, then the height at 163..=164 and the width at 165..=166,",
    "/// both big-endian. These two constants were named the other way round.",
    "/// [`crate::stripped::expand`] stayed byte-correct throughout -- it copies",
    "/// tdesktop's `stripped[1] -> 164, stripped[2] -> 166` -- but the swapped",
    "/// names had already produced a `dimensions()` that returned `(height, width)`",
    "/// under a doc comment promising `(width, height)`.",
    f"pub const HEIGHT_OFFSET: usize = {HEIGHT_OFFSET};",
    "/// Offset of the **width**'s low byte inside [`HEADER`]. See [`HEIGHT_OFFSET`].",
    f"pub const WIDTH_OFFSET: usize = {WIDTH_OFFSET};",
]

OUT.write_text("\n".join(lines) + "\n", encoding="ascii", newline="\n")
print(f"wrote {OUT}", file=sys.stderr)
